module:
  addanother: 0
  addtoany: 0
  admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  default_content: 0
  devel: 0
  disqus: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flexslider: 0
  flexslider_views: 0
  flippy: 0
  focal_point: 0
  geolocation: 0
  hal: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_style_quality: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  node: 0
  oc_custom: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  paragraphs_type_permissions: 0
  path: 0
  pathologic: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search: 0
  search404: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  superfish: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  oc: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  oc_patterns: 0
profile: oc
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
