definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
_core:
  default_config_hash: OP3IKYVCu9BaxpfY359e9hfT9IjmcDjVn2UHMNrBZ8A
