flippy_blog: 1
flippy_head_blog: 0
flippy_show_empty_blog: 0
flippy_prev_label_blog: 'Previous Article'
flippy_next_label_blog: 'Next Article'
flippy_first_last_blog: 0
flippy_first_label_blog: ''
flippy_last_label_blog: ''
flippy_loop_blog: 1
flippy_random_blog: 0
flippy_random_label_blog: ''
flippy_truncate_blog: ''
flippy_ellipse_blog: ''
flippy_press_swipe_blog: null
flippy_custom_sorting_blog: 1
flippy_sort_blog: created
flippy_order_blog: DESC
flippy_landing_page: 0
flippy_head_landing_page: 0
flippy_show_empty_landing_page: 0
flippy_prev_label_landing_page: ''
flippy_next_label_landing_page: ''
flippy_first_last_landing_page: 0
flippy_first_label_landing_page: ''
flippy_last_label_landing_page: ''
flippy_loop_landing_page: 0
flippy_random_landing_page: 0
flippy_random_label_landing_page: ''
flippy_truncate_landing_page: ''
flippy_ellipse_landing_page: ''
flippy_press_swipe_landing_page: null
flippy_custom_sorting_landing_page: 0
flippy_sort_landing_page: nid
flippy_order_landing_page: ASC
flippy_support_book: 0
flippy_head_support_book: 0
flippy_show_empty_support_book: 0
flippy_prev_label_support_book: ''
flippy_next_label_support_book: ''
flippy_first_last_support_book: 0
flippy_first_label_support_book: ''
flippy_last_label_support_book: ''
flippy_loop_support_book: 0
flippy_random_support_book: 0
flippy_random_label_support_book: ''
flippy_truncate_support_book: ''
flippy_ellipse_support_book: ''
flippy_press_swipe_support_book: null
flippy_custom_sorting_support_book: 0
flippy_sort_support_book: nid
flippy_order_support_book: ASC
flippy_profiles: 0
flippy_head_profiles: 0
flippy_show_empty_profiles: 0
flippy_prev_label_profiles: ''
flippy_next_label_profiles: ''
flippy_first_last_profiles: 0
flippy_first_label_profiles: ''
flippy_last_label_profiles: ''
flippy_loop_profiles: 0
flippy_random_profiles: 0
flippy_random_label_profiles: ''
flippy_truncate_profiles: ''
flippy_ellipse_profiles: ''
flippy_press_swipe_profiles: null
flippy_custom_sorting_profiles: 0
flippy_sort_profiles: nid
flippy_order_profiles: ASC
flippy_page: 0
flippy_head_page: 0
flippy_show_empty_page: 0
flippy_prev_label_page: ''
flippy_next_label_page: ''
flippy_first_last_page: 0
flippy_first_label_page: ''
flippy_last_label_page: ''
flippy_loop_page: 0
flippy_random_page: 0
flippy_random_label_page: ''
flippy_truncate_page: ''
flippy_ellipse_page: ''
flippy_press_swipe_page: null
flippy_custom_sorting_page: 0
flippy_sort_page: nid
flippy_order_page: ASC
flippy_event: 0
flippy_head_event: 0
flippy_show_empty_event: 0
flippy_prev_label_event: ''
flippy_next_label_event: ''
flippy_first_last_event: 0
flippy_first_label_event: ''
flippy_last_label_event: ''
flippy_loop_event: 0
flippy_random_event: 0
flippy_random_label_event: ''
flippy_truncate_event: ''
flippy_ellipse_event: ''
flippy_press_swipe_event: null
flippy_custom_sorting_event: 0
flippy_sort_event: nid
flippy_order_event: ASC
flippy_news: 0
flippy_head_news: 0
flippy_show_empty_news: 0
flippy_prev_label_news: ''
flippy_next_label_news: ''
flippy_first_last_news: 0
flippy_first_label_news: ''
flippy_last_label_news: ''
flippy_loop_news: 0
flippy_random_news: 0
flippy_random_label_news: ''
flippy_truncate_news: ''
flippy_ellipse_news: ''
flippy_press_swipe_news: null
flippy_custom_sorting_news: 0
flippy_sort_news: nid
flippy_order_news: ASC
_core:
  default_config_hash: ZIfzDOKW7ZAjKM3HAtOK08DhQMTQZDKU5qTvic8_t3Y
